### ISSUE TITLE
Build failes with Openssl 1.1.1

### ISSUE THREAD

**Issue by pizzamig** [mozilla/sccache#311]
The build process fails, if Openssl 1.1.1 is used.
The problem is not the crate openssl 0.10, but the crate openssl 0.9.24, that's too old to support OpenSSL 1.1.1
The old openssl crate is a direct dependency of native-tls 0.1.5, that's a dependency of:
* reqwest 0.8.8 (0.9 is available, asking for native-tls 0.2)
* hyper-tls 0.1.4 (dependency of reqwest, 0.3.x would solve the issue)
* tokio-tls 0.1.4 (deprecated)

Moving to a newer version of reqwest (aka unstable::async to async) would solve the issue

**Comment by brandonedens** [comment]
I'm also experiencing this issue.

I looked at updating hyper and reqwest but the changes are NOT trivial due to large modifications in both packages API. The http crate was introduced and now both packages reexport this API, deleting their old http definitions. There are lots of other changes too.

I'm continuing to try to update the source code, specifically the dist support but its slow progress.
Advice?

**Comment by clarcharr** [comment]
Any progress on fixing this?

**Comment by pizzamig** [comment]
Last time I checked, the only blocker left is reqwest 0.8.8
Unfortunately sccache uses unstable features of reqwest 0.8.8. Upgrading to 0.9 would mean a lot of work
On FreeBSD I solved the issue applying a patch the native-tls to use openssl 0.10.11 crate.

**Comment by bheisler** [comment]
This was preventing me from installing `sccache` on a couple of Arch Linux servers I have, but I was able to work around it. It looks like the current git version makes the `reqwest` dependency optional where it wasn't in the latest release. If you clone the repo and run `cargo install --path . --no-default-features` it builds and installs a binary that doesn't require any version of `openssl`, which is good enough for local-disk caching.

**Comment by doronbehar** [comment]
I've just tested this and I did experience this issue with v0.2.7 but not with v0.2.8. I think this can be closed unless someone can confirm it still persists.

**Comment by pizzamig** [comment]
v0.2.8 moved to reqwest 0.9 that has no issue with openssl 1.1.1, the issue is solved.

**Comment by marmistrz** [comment]
This issue persists on 0.2.9, probably due to the dependency on `selenium-rs`
* https://github.com/mozilla/sccache/blob/master/Cargo.lock#L1826
