### ISSUE TITLE
Silent fails building brave on windows with sccache

### ISSUE THREAD

**Issue by posix4e** [mozilla/sccache#62]
Here at www.brave.com we build our product on OSX and linux with sccache support. On windows setting the env for logging to trace seems to get us no extra logging. Also it seems as though all the calls are not supported

`browser-laptop-bootstrap>type npm-debug.log.2956940901                                                                                                                                                                                       D:\browser-laptop-bootstrap>sccache -s                                                                                  Max cache size                                                                                                10 GiB    Cache size                                                                                                   0 bytes    Cache location                                    Local disk: "C:\\Users\\posix4e\\AppData\\Local\\Mozilla\\sccache"    Compile requests                                                                                                 657    Compile requests executed                                                                                          0    Cache hits                                                                                                         0    Cache misses                                                                                                       0    Forced recaches                                                                                                    0    Cache read errors                                                                                                  0    Cache write errors                                                                                                 0    Compilation failures                                                                                               0    Cache errors                                                                                                       0    Successful compilations which could not be cached                                                                  0    Non-cacheable calls                                                                                                0    Non-compilation calls                                                                                              0    Unsupported compiler calls                                                                                       657    Average cache write                                                                                          0.000 s    Average cache read miss                                                                                      0.000 s    Average cache read hit                                                                                       0.000 s                       `                                                                                                     

How do i begin to debug this?

**Comment by luser** [comment]
I've used the debug logging on Windows, so it should work alright. If I had to guess I'd bet on your build using `-showIncludes` and sccache not handling that (https://github.com/mozilla/sccache/issues/47). I'm planning on fixing that soon, it breaks most CMake users.

**Comment by lilianmoraru** [comment]
`-showIncludes` is supported now.

**Comment by luser** [comment]
I'm going to assume this is fixed now. Please let me know if that's not the case!

**Comment by darkdh** [comment]
I'm still seeing all compile requests goes to `Unsupported compiler calls` by using `0.2.6` on Windows

**Comment by bridiver** [comment]
@luser are there other flags that are not cacheable?

**Comment by luser** [comment]
Yes, anything listed as `TooHard` [in the `ARGS` list](https://github.com/mozilla/sccache/blob/b33ed7e38927f87829d0fc11deae6cee173bee3a/src/compiler/msvc.rs#L204) will not be cached. Additionally, if the compile generates a PDB file with `-Z7` and the file already exists sccache will not cache the result.

**Comment by bridiver** [comment]
@luser I assume it normalizes `/flag` to `-flag` before checking?

**Comment by emerick** [comment]
Possibly related to #102? We use `clang-cl.exe` to compile Brave on Windows.

**Comment by emerick** [comment]
I built from master and that got me past the issue with `Unsupported compiler calls`, however all compilations are listed under `Non-cacheable calls` in `sccache --show-stats` now. In the log file, I see the following:

`DEBUG:sccache::server: check_compiler: Supported compiler
DEBUG:sccache::server: parse_arguments: CannotCache(multiple input files): ["/nologo", "/showIncludes", "-imsvcc:\\program files (x86)\\microsoft visual studio\\2017\\professional\\vc\\tools\\msvc\\14.11.25503\\atlmfc\\include", "-imsvcc:\\program files (x86)\\microsoft visual studio\\2017\\professional\\vc\\tools\\msvc\\14.11.25503\\include", "-imsvcc:\\program files (x86)\\windows kits\\10\\include\\10.0.15063.0\\ucrt", "-imsvcc:\\program files (x86)\\windows kits\\10\\include\\10.0.15063.0\\shared", "-imsvcc:\\program files (x86)\\windows kits\\10\\include\\10.0.15063.0\\um", "-imsvcc:\\program files (x86)\\windows kits\\10\\include\\10.0.15063.0\\winrt", "-DBASE_I18N_IMPLEMENTATION", "-DV8_DEPRECATION_WARNINGS", "-DUSE_AURA=1", "-DNO_TCMALLOC", "-DFULL_SAFE_BROWSING", "-DSAFE_BROWSING_CSD", "-DSAFE_BROWSING_DB_LOCAL", "-DCHROMIUM_BUILD", "-DFIELDTRIAL_TESTING_ENABLED", "-DCR_CLANG_REVISION=\"325667-1\"", "-D_HAS_EXCEPTIONS=0", "-D__STD_C", "-D_CRT_RAND_S", "-D_CRT_SECURE_NO_DEPRECATE", "-D_SCL_SECURE_NO_DEPRECATE", "-DDEPRECATEDENUMERATOR(x)=[[deprecated(x)]]", "-D_ATL_NO_OPENGL", "-D_WINDOWS", "-DCERT_CHAIN_PARA_HAS_EXTRA_FIELDS", "-DPSAPI_VERSION=1", "-DWIN32", "-D_SECURE_ATL", "-D_USING_V110_SDK71_", "-DBRAVE_CHROMIUM_BUILD", "-DWIN32_LEAN_AND_MEAN", "-DNOMINMAX", "-D_UNICODE", "-DUNICODE", "-DNTDDI_VERSION=0x0A000002", "-D_WIN32_WINNT=0x0A00", "-DWINVER=0x0A00", "-DNDEBUG", "-DNVALGRIND", "-DDYNAMIC_ANNOTATIONS_ENABLED=0", "-DU_USING_ICU_NAMESPACE=0", "-DU_ENABLE_DYLOAD=0", "-DU_STATIC_IMPLEMENTATION", "-DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_FILE", "-DUCHAR_TYPE=wchar_t", "-I../../brave/chromium_src", "-I../..", "-Igen", "-I../../third_party/ced/src", "-I../../third_party/icu/source/common", "-I../../third_party/icu/source/i18n", "-Wno-builtin-macro-redefined", "-D__DATE__=", "-D__TIME__=", "-D__TIMESTAMP__=", "-fcolor-diagnostics", "-Xclang", "-mllvm", "-Xclang", "-instcombine-lower-dbg-declare=0", "/Gy", "/FS", "/bigobj", "/d2FastFail", "/Zc:sizedDealloc-", "-fmsc-version=1911", "-m64", "/W4", "-Wimplicit-fallthrough", "-Wthread-safety", "/WX", "/utf-8", "/wd4091", "/wd4127", "/wd4251", "/wd4275", "/wd4312", "/wd4324", "/wd4351", "/wd4355", "/wd4503", "/wd4589", "/wd4611", "/wd4100", "/wd4121", "/wd4244", "/wd4505", "/wd4510", "/wd4512", "/wd4610", "/wd4838", "/wd4995", "/wd4996", "/wd4456", "/wd4457", "/wd4458", "/wd4459", "/wd4702", "-Wno-unknown-pragmas", "-Wno-microsoft-cast", "-Wno-missing-field-initializers", "-Wno-unused-parameter", "-Wno-c++11-narrowing", "-Wno-covered-switch-default", "-Wno-unneeded-internal-declaration", "-Wno-inconsistent-missing-override", "-Wno-undefined-var-template", "-Wno-nonportable-include-path", "-Wno-address-of-packed-member", "-Wno-unused-lambda-capture", "-Wno-user-defined-warnings", "-Wno-enum-compare-switch", "-Wno-null-pointer-arithmetic", "/Z7", "-fstandalone-debug", "/MT", "-Xclang", "-add-plugin", "-Xclang", "find-bad-constructs", "-Wheader-hygiene", "-Wstring-conversion", "-Wtautological-overlap-compare", "/O2", "/Ob2", "/Oy-", "/Zc:inline", "/Gw", "/wd4267", "/TP", "/wd4577", "/GR-", "/c", "../../base/i18n/icu_util.cc", "/Foobj/base/i18n/icu_util.obj", "/Fdobj/base/i18n_cc.pdb"]
`

Feels like something is throwing the parser off in this scenario.

**Comment by luser** [comment]
My guess would be the `-Xclang` arguments, one of the arguments following them doesn't start with a - and I don't know that the clang-cl argument parser knows to handle those.

**Comment by emerick** [comment]
From what we've been able to diagnose, it seems that the `-Xclang` argument with the missing `-` is one problem and the conversion of `/showIncludes` to `--show-includes` is another problem (because the version of `clang-cl.exe` that we're using only supports the `/showIncludes` syntax).

**Comment by emerick** [comment]
It sounds like the second issue I mentioned above (with `-showIncludes`) could be a manifestation of #246. It doesn't appear that we're passing `-E`, but the symptoms look identical from what I can tell.

**Comment by bridiver** [comment]
I believe that both work in clang master, but the current version (7) only recognizes `/showIncludes` - https://clang.llvm.org/docs/UsersManual.html

**Comment by fxb** [comment]
@emerick `sccache` is passing `-E` to preprocess, resulting in `-E` being passed in combination with `/showIncludes`, which `clang-cl.exe` didn't support until my recent patch: https://reviews.llvm.org/rC331533

**Comment by emerick** [comment]
@fxb Ahh that makes sense, thank you for explaining.

**Comment by emerick** [comment]
Now that we're using a version of `clang-cl.exe` with https://reviews.llvm.org/rC331533, this looks like it may be working (pending a few more tests that I'm running). Three additional changes were required on our side:

1. Don't pass the `-XClang find-bad-constructs` arg, as `sccache` interprets the argument as an additional source file. (This feels like a bug to me. Should I create an issue to track this?)
1. Don't pass `/Brepro`, as it causes the following error when compiling with `sccache` enabled: `warning: argument unused during compilation: '-mno-incremental-linker-compatible'`. Not sure if this is a bug in `sccache` or just a sign of incompatible settings in our build options. Any thoughts?
1. Don't pass `/Fp`, as this setting seems to conflict with `sccache`.

**Comment by luser** [comment]
> Don't pass the -XClang find-bad-constructs arg, as sccache interprets the argument as an additional source file. (This feels like a bug to me. Should I create an issue to track this?)

We hit this same issue when we switched Firefox builds to clang-cl, but I haven't fixed it yet. I filed: https://github.com/mozilla/sccache/issues/262

> Don't pass /Brepro, as it causes the following error when compiling with sccache enabled: warning: argument unused during compilation: '-mno-incremental-linker-compatible'. Not sure if this is a bug in sccache or just a sign of incompatible settings in our build options. Any thoughts?

I had never heard of this compiler option before (neat!) but my guess would be that clang-cl doesn't like if you pass it when running just the preprocessor. When sccache runs the preprocessor it passes known preprocessor arguments [as well as any unknown options](https://github.com/mozilla/sccache/blob/df13487fad5874f144ce1316c999170ac3803237/src/compiler/msvc.rs#L283). Some brief local testing shows this to be the case, [I filed an issue about this](https://github.com/mozilla/sccache/issues/264):
```
ted@DESKTOP-32V9ND8 /c/build
$ cat test.c
int foo() { return 0; }

ted@DESKTOP-32V9ND8 /c/build
$ ~/.mozbuild/clang/bin/clang-cl.exe -Fotest.obj -c test.c

ted@DESKTOP-32V9ND8 /c/build
$ ~/.mozbuild/clang/bin/clang-cl.exe -E test.c
# 1 "test.c"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 332 "<built-in>" 3
# 1 "<command line>" 1
# 1 "<built-in>" 2
# 1 "test.c" 2
int foo() { return 0; }

ted@DESKTOP-32V9ND8 /c/build
$ ~/.mozbuild/clang/bin/clang-cl.exe -E test.c -Brepro
clang-cl.exe: warning: argument unused during compilation: '-mno-incremental-linker-compatible' [-Wunused-command-line-argument]
# 1 "test.c"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 332 "<built-in>" 3
# 1 "<command line>" 1
# 1 "<built-in>" 2
# 1 "test.c" 2
int foo() { return 0; }
```

> Don't pass /Fp, as this setting seems to conflict with sccache.

Right, we [explicitly don't support caching /Fp](https://github.com/mozilla/sccache/blob/df13487fad5874f144ce1316c999170ac3803237/src/compiler/msvc.rs#L218). It would be nice if sccache exposed info about why it didn't cache compiles outside of its internal logs, for sure. I filed a new issue for that: https://github.com/mozilla/sccache/issues/263

**Comment by bridiver** [comment]
maybe a config file would be useful so you could add options you want it to pass through or strip (at your own risk)?

**Comment by emerick** [comment]
@luser Thanks for the feedback and entering issues, we appreciate it!
