### ISSUE TITLE
Unable to install sccache with cargo

### ISSUE THREAD

**Issue by agile-jtdressel** [mozilla/sccache#924]
I'm no longer able to install sccache with cargo on either a x86_64 or arm mac.

I believe this is related to the [yanking of lru-disk-cache](https://github.com/rust-lang/crates.io-index/commits/master/lr/u-/lru-disk-cache).

```
cargo install sccache
    Updating crates.io index
  Installing sccache v0.2.14
error: failed to compile `sccache v0.2.14`, intermediate artifacts can be found at `/var/folders/b0/n2dvhj813014d3pd009dw0cw0000gn/T/cargo-installgnrFOb`

Caused by:
  no matching package named `lru-disk-cache` found
  location searched: registry `https://github.com/rust-lang/crates.io-index`
  required by package `sccache v0.2.14`
```

**Comment by glandium** [comment]
Sigh... that doesn't quite match what crates.io itself says is supposed to happen:
```
This crate has been yanked, but it is still available for download for other crates that may be depending on it. 
```
(https://crates.io/crates/lru-disk-cache)

**Comment by StormRat** [comment]
lru-disk-cache  has been yanked...
why ?..

https://github.com/rust-lang/crates.io-index/commit/3c6e38aed4659b115c81661382b72385145e8eb1

**Comment by glandium** [comment]
> lru-disk-cache has been yanked...
> why ?..
See #916

**Comment by glandium** [comment]
Fixed by unyanking 0.4.1.

**Comment by nickbroon** [comment]
I'm still seeing this issue when trying to install version 0.2.13, which the last version that will work with 1.41.1 rustc that's available on Debian 10 (I'm constrained to this version, not using rustup to install a newer compiler)

```
cargo install --version 0.2.13 sccache
```
    Updating crates.io index
 Downloading crates ...
  Downloaded sccache v0.2.13
  Installing sccache v0.2.13
error: failed to compile `sccache v0.2.13`, intermediate artifacts can be found at `/tmp/cargo-installoqqd84`
Caused by:
  no matching package named `lru-disk-cache` found
location searched: registry `https://github.com/rust-lang/crates.io-index`
required by package `sccache v0.2.13`
```

**Comment by nickbroon** [comment]
Answering myself... ;-)
Need to use locked `cargo install --version 0.2.13 --locked sccache`
